apiVersion: v1
kind: Service
metadata:
  name: sea-retailer-api
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: sea-retailer-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
