apiVersion: v1
kind: Service
metadata:
  name: sea-retailer-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: sea-retailer-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
