{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sea-retailer-secrets
  namespace: {{ .Values.global.namespace }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "false"
  labels:
    app.kubernetes.io/name: sea-retailer
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: sealed-secrets
spec:
  encryptedData:
    postgres-password: {{ .Values.sealedSecrets.postgresPassword | quote }}
    clickhouse-password: {{ .Values.sealedSecrets.clickhousePassword | quote }}
    keycloak-admin-password: {{ .Values.sealedSecrets.keycloakAdminPassword | quote }}
    jwt-signing-key: {{ .Values.sealedSecrets.jwtSigningKey | quote }}
  template:
    type: Opaque
    metadata:
      name: sea-retailer-secrets
      namespace: {{ .Values.global.namespace }}
      labels:
        app.kubernetes.io/name: sea-retailer
        app.kubernetes.io/component: secrets
        app.kubernetes.io/managed-by: sealed-secrets
{{- end }}
