apiVersion: v1
kind: Secret
metadata:
  name: sea-retailer-secrets
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  clickhouse-password: {{ .Values.secrets.clickhousePassword | quote }}
  keycloak-admin-password: {{ .Values.secrets.keycloakAdminPassword | quote }}
